### ISSUE TITLE
Is there a feature that continues recording even when moving the Unity scene?

### ISSUE THREAD

**Issue by Seul9** [natsuite/NatSuite-Examples#18]
I purchase and use'NatCorder-Video Recording API' through the Unity Asset Store.
It works fine for 1 scene.
But when I switch the scene to a->b DontDestroyOnLoad(GameObject)
Even if you proceed to, recording in scene a does not last until b.

Is there a way to make the recording last even if I switch scenes?

**Comment by olokobayusuf** [comment]
This won't work, because when you switch scenes the game camera you are recording from also gets destroyed. You should either keep your recording in a scene, or re-engineer your scenes so that any game cameras and audio listeners or audio sources being recorder do not get destroyed when the scene is switched.

**Comment by Seul9** [comment]
If the camera is changed from a normal camera to an AR camera, is it difficult to continue recording?

**Comment by olokobayusuf** [comment]
> If the camera is changed from a normal camera to an AR camera, is it difficult to continue recording?

If you want to switch recording cameras during recording, you can destroy the current `CameraInput` and create a new one with your new camera. But you must use the same clock:
```csharp
// Destroy current camera input
cameraInput.Dispose();
// Create new one
cameraInput = new CameraInput(mediaRecorder, clock, newCamera);
```

If you are switching to an AR camera, you must make sure that your recording resolution (when you create the recorder) has the same aspect ratio as the screen. This is because AR cameras don't support dynamic scaling, so if the recording resolution is different, it will look stretched.
