### ISSUE TITLE
How to record a video with a low framerate?

### ISSUE THREAD

**Issue by derwaldgeist** [natsuite/NatSuite-Examples#24]
I'm trying to record a low-resolution, animated GIF video with a low frame rate, i.e. max 2-5 fps. It should playback at the same speed as it was recorded. Since it is solely being used as a thumbnail, it's ok if the playback speed is quite stuttering.

I tried to set it up like this:

```cs
var fps = 2;
var frameDuration = 0.5f; // = 1 / fps
var clock = new FixedIntervalClock(fps);
var gifRecorder = new GIFRecorder(width, height, frameDuration);
var cameraInput = new CameraInput(gifRecorder, clock, myCamera);
``` 

My expectation is that in this setup, only 2 frames are shot per second, so only 2 images per second will be included in the resulting GIF.

However, whatever value I use for fps, the GIF will always contain all images at max fps of the camera feed. Only the frameDuration has an impact on the resulting GIF (if it's lower, the speed is faster).

In effect, the GIFs always have the same size, which only depends on the width and height, but not on the frame rate. What am I doing wrong here?

(I also noted that NatCam crashes Unity if I try to set the fps to 1.)

**Comment by derwaldgeist** [comment]
Just noticed it's the same for the MP4 recorder. Even if I set the framerate to 1 fps, the full frame rate of the camera is being recorded.

**Comment by olokobayusuf** [comment]
Hey there @derwaldgeist , sorry for the late response on this. I have inline responses below:

> However, whatever value I use for fps, the GIF will always contain all images at max fps of the camera feed. Only the frameDuration has an impact on the resulting GIF (if it's lower, the speed is faster).

This is expected behaviour. If your app is running at say 30FPS, and you create a `CameraInput` to record, the camera input will always render the camera(s) on every Unity update (i.e., at the exact frame rate of your app).  What you are trying to do is record frames less frequently than the app's frame rate, in which case you can use the [frameSkip property of the CameraInput class](https://docs.natsuite.io/natcorder/api/camerainput#skipping-frames). The included GIF recording example uses this to create the classic low-FPS GIF feel.

> (I also noted that NatCam crashes Unity if I try to set the fps to 1.)

This could be because the native recording API rejects that value as being out of some nominal range. I'll need more info on the crash to know for sure.

> Even if I set the framerate to 1 fps in the MP4Recorder constructor like this:

On the MP4 and HEVC recorders, the frame rate you pass to the constructor is effectively meaningless. What determines the frame rate of the output video [is the difference between consecutive timestamps](https://docs.natsuite.io/natcorder/api/mp4recorder#committing-video-frames), and the passage of time within the recorded frames themselves. This is one reason why recording clocks play an important role in recording.

**Comment by derwaldgeist** [comment]
Hi Yusuf, thanks for your response!

> you can use the frameSkip property of the CameraInput class

Interesting, did miss that. Will try it out!

> On the MP4 and HEVC recorders, the frame rate you pass to the constructor is effectively meaningless.

Ok, this is a bit confusing, since the documentation states that the framerate controls - well - the framerate :-)

> This is one reason why recording clocks play an important role in recording.

If I understand you correctly, you're basically saying that I can control the framerate by using a fixed interval clock instead of a real-time clock? If so, why does this approach not work for the gif recorder, and the skip frames flag has to be set instead. This seems to be a bit inconsistent to me. Is there a technical reason for this?

**Comment by olokobayusuf** [comment]
> Interesting, totally missed that option in the docs. Thanks. Will try it out! I guess I will have to set this flag immediately after initializing the CameraInput?

You can set it anytime, but you'd usually wanna do so after creating the camera input.

> Ok, this is a bit confusing, since the documentation states that the framerate controls - well - the framerate :-)

The frame rate argument passed to the `MP4Recorder` and `HEVCRecorder` is really a hint for the encoder.

> If I understand you correctly, you're basically saying that I can control the framerate by using a fixed interval clock instead of a real-time clock?

Yes, you can use a `FixedIntervalClock` to guarantee a fixed frame rate in the output video file. A realtime clock will always generate videos at a variable frame rate (because of tiny shifts and hiccups here and there).

> If so, why does this approach not work for the gif recorder, and the skip frames flag has to be set instead.

[The GIFRecorder doesn't use timestamps](https://docs.natsuite.io/natcorder/api/gifrecorder#committing-frames). What controls timing is the `frameDuration` parameter you pass to the constructor. The MP4 and HEVC recorders are the only ones that rely on timestamps; GIF, WAV, and JPG don't.

Skipping frames is a totally different concept. When you record with a `CameraInput`, its default behaviour is to record a frame on every Unity `Update`. Unity updates at your app's frame rate, so you'll have a lot more frames than you actually want to show up in your recording, especially when it comes to animated GIF's. You can use frame skipping to reduce the number of consecutive **Unity updates** that translate into recorded frames.

> This seems to be a bit inconsistent to me. Is there a technical reason for this? And would the CameraInput's frame skipping work for MP4 as well?

You can use frame skipping with MP4 recorders, or any other recorders. A very common use case for this is when your app renders at 60FPS, but for performance or other reasons, you want your recording to be at 30FPS. You would then set the frame skip to 1 in this case, so that only every other *game frame* ends up in the video.

In this case, messing with timestamps won't help you, because pretending that a 60FPS stream has a frame interval of 1/30s would only alter the perception of the flow of time within the video.
