### ISSUE TITLE
GIFRecorder: Crop Camera Input

### ISSUE THREAD

**Issue by derwaldgeist** [natsuite/NatSuite-Examples#26]
My camera input feed is a portrait mode smartphone screen, but I would like to crop the GIF to a square. If I pass in the same values for width and height, I get a square, and in the macOS editor it is cropped from the middle, which is exactly what I want. On iOS, however, the image is squashed. It's still a square, but distorted. Is there a way to prevent this? Haven't tested Android yet.

**Comment by olokobayusuf** [comment]
> My camera input feed is a portrait mode smartphone screen, but I would like to crop the GIF to a square. If I pass in the same values for width and height, I get a square, and in the macOS editor it is cropped from the middle, which is exactly what I want. On iOS, however, the image is squashed. It's still a square, but distorted. Is there a way to prevent this? Haven't tested Android yet.

Hey @derwaldgeist , are you recording in AR by any chance? In AR, the aspect ratio of the recording has to match that of the screen because of ARFoundation renders the camera background.

**Comment by derwaldgeist** [comment]
Yes, we're recording the AR camera feed.

**Comment by olokobayusuf** [comment]
Right this explains why. AR frameworks override how the camera renders (especially because of the view projection matrices and camera background) so your recording has to have the same aspect ratio as the screen. [NatCorder Performance Extensions](https://github.com/natsuite/NatCorder-Performance-Extensions) has a WIP frame cropping implementation, but it isn't complete yet.

**Comment by derwaldgeist** [comment]
Ok, thanks for the info. Wasn't aware of the performance extensions, sounds good, looking forward to it!
