### ISSUE TITLE
torchEnabled Always Returns False

### ISSUE THREAD

**Issue by seantibb** [natsuite/NatSuite-Examples#6]
I purchased NatDevice earlier today and updated my code to call the torch to enable/disable based on a button click. Unfortunatetly, I am seeing the same behavior I saw before with NatCam where `device.torchEnabled` always returns `false`. I have attached the VS debugger and looped through this code many, many times and the behavior is always the same. Please let me know if something looks incorrect in my code below or if I can be of further assistance to get this figured out.

I have confirmed this on the following devices:
Pixel 2 -- Android 10 Patch Level 5 February 2020
Galaxy S8 -- Android 9 Patch Level 1 January 2020
HTC One -- Android 7
HTC One -- Android 5

```
using System;
using UnityEngine;
using UnityEngine.EventSystems;
using NatDevice;

public class FlashlightButtonClickHandler : MonoBehaviour, IPointerClickHandler
{
    private string TAG = "[rdhj][FlashlightButtonClickHandler]";

    private MediaDeviceQuery deviceQuery;

    public void OnPointerClick(PointerEventData eventData)
    {
        Debug.Log(TAG + "[OnPointerClick] received eventData");
        try
        {
            deviceQuery = new MediaDeviceQuery(MediaDeviceQuery.Criteria.RearFacing);
#if UNITY_EDITOR
            deviceQuery = new MediaDeviceQuery(MediaDeviceQuery.Criteria.GenericCameraDevice);
#endif
            //CHECK TO SEE IF THE FLASHLIGHT IS ON, IF SO, TURN IT OFF ELSE TURN IT ON
            if (deviceQuery.currentDevice is CameraDevice device)
            {
                try
                {
                    //device.flashMode = device.flashMode == FlashMode.On ? FlashMode.Off : FlashMode.On;
                    if (device.torchSupported)
                    {
                        if (device.torchEnabled)
                            device.torchEnabled = false;
                        else
                            device.torchEnabled = true;
                    }
                    //TODO: change icon based on current mode
                    //flashIcon.color = device.flashMode == FlashMode.On ? Color.white : Color.gray;
                }
                catch (Exception e)
                {
                    Debug.LogError(TAG + "[OnPointerClick] exception: " + e.StackTrace);
                }
            }
            /*
            NatCam.DeviceCamera cam = NatCam.DeviceCamera.Cameras[0];
            if (cam.TorchEnabled)
                cam.TorchEnabled = false;
            else
                cam.TorchEnabled = true;
                */
        }
        catch (System.Exception e)
        {
            Debug.LogError(TAG + "[OnPointerClick] exception: " + e.Message);
        }


    }
}
```

**Comment by olokobayusuf** [comment]
Hey there Sean. A few things to note:
- Creating a new device query will create new `CameraDevice` instances, each of which will have a totally reset state (even though they might reference the same hardware camera). You should only ever create queries sparingly, and instead keep a reference to the one you've created. Creating them is expensive.
- Because of the above point, your method will never see `torchEnabled` to be `true`. You can fix this by keeping a persistent device query and checking/setting the state on the `query.currentDevice`.
- Also, no need for the exception handling; creating a device query will never throw an exception. Similarly, setting the camera parameters (like torch) will never throw an exception.

Fix your code and let me know if this fixes your issue.,
